m1k1o/neko

.m1k1o/chromium/Dockerfile, .m1k1o/chromium/openbox.xml, .m1k1o/chromium/supervisord.conf
This pull request implements https://github.com/nurdism/neko/issues/98 by replacing the currently used build of Chromium from the Debian repositories with a custom build from [Woolyss](https://chromium.woolyss.com/) which has support for proprietary codecs like HEVC/x265.
=> Replace official Chromium build with custom build from Woolyss

.m1k1o/base/Dockerfile, .m1k1o/chromium/Dockerfile
Chromium, see: https://github.com/macchrome/linchrome/releases/tag/v84.0.4147.125-r768962-portable-ungoogled-Lin64
Go, see: https://blog.golang.org/go1.15
=> Update Chromium and Go

.m1k1o/base/Dockerfile
This pull request changes the NodeJS base image tag from `12.18-buster-slim` to `12-buster-slim` to remove the need to manually keep up with new 12.x minor version releases.
The `12-buster-slim` tag is always [equivalent to the latest 12.x minor version](https://hub.docker.com/_/node) (currently 12.19), just like the `1.15-buster` tag of the Go base image is always [equivalent to the latest 1.15.x minor version](https://hub.docker.com/_/golang) (currently 1.15.3).
=> Update NodeJS base image to 12.19

.m1k1o/chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v87.0.4280.88-r812852-portable-ungoogled-Lin64
=> Dockerfile: Update Chromium to v87.0.4280.88

.m1k1o/chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v88.0.4324.96-r827102-portable-ungoogled-Lin64
=> Dockerfile: Update Chromium to v88.0.4324.96

server/internal/gst/gst.go
if h264enc and openh264 is installed it lead to both strings in the gstreamer pipeline which resulted in no video output
If you prefer I will send this pull request against nurdism/neko instead.
=> Removed double h264 encoding

server/internal/gst/gst.go, server/internal/webrtc/peer.go, server/internal/webrtc/webrtc.go
It seems that the reason for the small lags was a buffering problem of the encoder.
With this PR I no lags at all (tested on a i7-2600k)
Further I readded the rtcp listener, since in the new pion examples they are still implemented and seem to be necessary for the functionality ( https://github.com/pion/webrtc/blob/33d953e1eb58bb308128b011677cf60f5e1d261b/examples/reflect/main.go#L34  //  https://github.com/pion/webrtc/blob/33d953e1eb58bb308128b011677cf60f5e1d261b/examples/reflect/main.go#L73 )
=> removes small lags from video live streamings

.m1k1o/chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v88.0.4324.182-r827102-portable-ungoogled-Lin64
=> Dockerfile: Update Chromium to v88.0.4324.182

.m1k1o/chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v89.0.4389.90-r843830-portable-ungoogled-Lin64
=> Dockerfile: Update Chromium to v89.0.4389.90

server/internal/remote/manager.go, server/internal/xorg/xorg.c, server/internal/xorg/xorg.go, server/internal/xorg/xorg.h
First try, still crashes bit seems to work as expected otherwise.
=> pressing key with multiple pressed keys

.m1k1o/ungoogled-chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v90.0.4430.85-r857950-portable-ungoogled-Lin64
=> Dockerfile: Update Ungoogled Chromium to v90.0.4430.85

.m1k1o/ungoogled-chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v90.0.4430.93-r857950-portable-ungoogled-Lin64
=> Dockerfile: Update Ungoogled Chromium to v90.0.4430.93

.m1k1o/ungoogled-chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v90.0.4430.212-r857950-portable-ungoogled-Lin64
=> Dockerfile: Update Ungoogled Chromium to v90.0.4430.212

.m1k1o/ungoogled-chromium/Dockerfile
See https://github.com/macchrome/linchrome/releases/tag/v91.0.4472.101-r870763-portable-ungoogled-Lin64
This release contains fixes for the zero day vulnerabilities described [here](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop.html).
=> Dockerfile: Update Ungoogled Chromium to v91.0.4472.101

server/internal/webrtc/webrtc.go
With `NEKO_VP8: 'false'`, `NEKO_VP9: 'false'` and `NEKO_H264: 'true'` under `docker-compose.yaml`'s `environment` tag, the video stream would be encoded in H.264 for WebRTC.
But in `server/internal/webrtc/webrtc.go`, with the current `profile-level-id=42001f`, Firefox 94.0.2 (on the client-side) won't accept the WebRTC video stream:
https://github.com/m1k1o/neko/blame/c97b1fc4541caabf6b00331d081b02d2f9c58751/server/internal/webrtc/webrtc.go#L318
The symptom is that Firefox client displays a "Disconnected - connection timeout" message (after waiting for 15s) on the top left corner when logging in (despite entering the correct password). (Chrome works just fine btw.)
In the mean time, the following is found in the container log:
```
neko_1  | 2021-12-05 10:04:09,952 DEBG 'neko' stdout …
```
=> Set WebRTC video codec H.264 `profile-level-id` to `42e01f` to be compatible with Firefox clients

docs/changelog.md, docs/getting-started/configuration.md, server/internal/broadcast/manager.go, server/internal/types/config/broadcast.go
This PR adds a new configuration option to set a default endpoint for broadcasting.
Adding the default endpoint will automatically start broadcasting when the server starts.
Format:
```
NEKO_BROADCAST_DEFAULT_ENDPOINT="rtmp://your-rtmp-endpoint/live"
```
```
neko serve --broadcast_default_endpoint "rtmp://your-rtmp-endpoint/live"
```
=> Feature: default broadcast endpoint config option

.docker/base/Dockerfile, .docker/base/add-render-group.sh, .docker/base/supervisord.conf, server/internal/gst/gst.go, server/internal/remote/manager.go, server/internal/types/config/remote.go
Hardware accelerated encoding using Intel QuickSync via VAAPI. Tested VP8 and H264 on a Coffee Lake CPU. 
Adding support for AMD/VAAPI *should* AFAICT just be a matter of further adding the necessary packages. The PR leaves open the possibility of adding NVENC down the line - the hw encoder to use is requested via env var.
The end user is required to (via docker-compose or whatever else):
1. pass `/dev/dri` to the container
2. pass an env var `NEKO_HWENC=VAAPI`
3. optionally pass an env var `RENDER_GID=<gid>` with the group id of the render user (or the user that owns `/dev/dri/renderD*`) - it'll be fetched automatically otherwise (as long as `/dev/dri` is passed through) but it's not well tested yet
*Sometimes* on container startup X will throw a fit with (possibly non-exhaustive list): …
=> Hardware accelerated encoding using Intel QuickSync via VAAPI

client/src/components/video.vue, client/src/types/navigator.keyboard.d.ts, client/src/utils/index.ts
When using fullscreen mode, hitting the escape key will exit out of fullscreen mode.  To stay in fullscreen mode but pass the escape key through, we can use the Keyboard API to require the escape key be held down https://wicg.github.io/keyboard-lock/#escape-key.
Tested in Chrome which supports Keyboard API and Firefox which does not https://caniuse.com/?search=navigator.keyboard with no errors in either case.
=> Use Keyboard API to lock screen for supported browsers

client/src/app.vue, client/src/components/video.vue, docs/getting-started/README.md
see #261
separate cast mode and embed mode. 
in cast and embed mode only video is visible.
in embed mode there are visible controls on video.
it is potential breaking change, anyone who used cast mode now most likely will need use embed mode.
=> hide buttons in cast mode #261

client/src/components/video.vue
see  #261
i disabled security option for requiring user interaction for playing audio on browser level. if cast option is set i don't mute audio, but then when security option is enabled then no video is started so i changed video.play() to retry with mute if cast is set
=> add autoplay audio if cast is set #261

client/src/components/video.vue
see #261
on my touch device i can't 'drag' (eg. select text). i added onTouch events to onMouse events and it is working now. but im not sure if it is relay not working or it should work but my setup is broken.
=> add touch events on touch monitor #261

.docker/base/Dockerfile.nvidia, server/internal/capture/pipelines.go
Hi,
I had a similar problem with the rpi pipeline back in the day.
I added h264parse and it worked like expected.
I took every 3 seconds as a value for the refresh frame.
I changed the profile and the profile to High Quality since it should be fast enough on nvenc either way. But some experimenting could be done here.
=> Nvidia nvenc

.docker/base/Dockerfile.nvidia, docs/changelog.md, docs/getting-started/configuration.md, server/internal/capture/pipelines.go, server/internal/config/capture.go
Nvidia hardware encoding using `nvh264enc`. Can be merged when following issue is solved:
There is still a problem when using `nvh264enc` pipeline, if its already running and someone joins that pipeline, no video is shown until pipeline is restarted. Solution would be to restart pipeline everytime when somesone joins. But that is rather hack than solution.
Discussion about this problem is here: https://github.com/m1k1o/neko/issues/193
=> Add NVENC support for gstreamer

docs/getting-started/troubleshooting.md
A small elaboration is provided at troubleshooting page where the usage of `NAT1TO1` is somewhat confusing for `NAT1T01`.
=> update docs to explicitly differentiate between letter O and zero

client/src/app.vue
When opening the page in a browser, before commit 98ba32c574a53d6e1f6ec2e2b3613c8a0383c830 the browser (firefox or chrome) would remember the Volume level from your previous session.
That commit added a URL parameter to set the volume using ?volume=value 
That commit causes the volume to be set to max every time the page is loaded due to the following line:
const numberParam = parseFloat(new URL(location.href).searchParams.get('volume') || '1.0')
This commit simply adds a check for the volume parameter before setting the variable, so if you don't set ?volume in the URL, it will use the last sessions value.
If any more info is needed, or a change must be made, please let me know.
=> Add check for volume parameter in URL before setting volume

server/internal/capture/gst/gst.c
vsprintf() is dangerous, and can overflow easily, especially with small buffers like the 100 byte one that was being used. This changes the buffer size to a more sane 4KiB, and uses vsnprintf() to automatically concatenate a large log message instead of overflowing and crashing.
=> Fix buffer overflow in Gstreamer log function

server/internal/capture/gst/gst.go, server/internal/capture/manager.go
The gstreamer documentation is not particularly amazing on whether or not this is necessary, but it's clear that some gstreamer events will not be delivered to their handlers without a running glib loop. This runs one loop for all pipelines, which should be more than enough.
Disclaimer: This may conflict in demodesk/neko with the dragdrop feature. Anyone backporting this bug fix to that repo should investigate whether the loop created by `gtk_main()` will conflict with this one before blindly porting.
Fixes #380
Fixes #284
=> Add a glib main loop to capture manager

docs/contributing.md
=> Add missing libgstreamer-plugins-base1.0-dev to compile dependency docs

.gitignore, client/src/neko/base.ts, client/src/neko/events.ts, client/src/neko/index.ts, client/src/neko/messages.ts, server/internal/config/websocket.go, server/internal/types/event/events.go, server/internal/types/message/messages.go, server/internal/websocket/handler/handler.go, server/internal/websocket/handler/session.go, server/internal/websocket/websocket.go
When neko runs behind an L3 or L7 load balancer, it may encounter TCP connection timeout issues. Sometimes the maximum timeout cannot be set to a very high value, causing neko to frequently reconnect. Moreover, I believe that setting too large a timeout value might result in the server retaining too many unused connections.
This PR adds the event `client/heartbeat` and ignores this event in the backend. 
The heartbeat is configured through the environment variable `NEKO_HEARTBEAT_INTERVAL` or the configuration setting `heartbeat_interval`, with a default value of `120` seconds. When the value is less than or equal to `0`, the heartbeat mechanism is disabled.
After `heartbeat_interval` is passed to the frontend via the `system/init` event, the frontend starts sending heartbeat events at …
=> feat(general): add heartbeat to websocket control

.docker/firefox/policies.json
added `browser.tabs.allowTabDetach` to prevent drag-detaching tabs into seperate windows
=> Update Firefox policies.json (prevent detaching tabs)

client/src/components/menu.vue, client/src/plugins/i18n.ts
This PR adds the feature requested on https://github.com/m1k1o/neko/issues/55
- Added a watcher to save the selected language to `localStorage` on change.
- Implemented browser language detection to set the default language based on user settings or browser preferences.
=> feat(i18n): enhance language management by saving user preference and auto detect browser language

client/src/app.vue, client/src/components/connect.vue
This PR adds phone layout as suggested in https://github.com/m1k1o/neko/issues/381 with a difference, that in portrait mode, the chat will be shown onm 60% of the screen with 40% being the video.
https://github.com/user-attachments/assets/f2ddc1f0-088b-4d35-a8d0-a1c6a5fb96f3
=> Scroll to chat on mobile

README.md
Previous link of /v3/installation/examples was broken.
=> fix: link to Examples in docs/v3

build
Fixing a build error -- docker does not allow mounting `./` as source volume.
```
docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
=> Fix docker volume mount error in build script.

build
```sh
% ./build
2025-04-22 10:21:07 - [NEKO] - Using docker build
2025-04-22 10:21:07 - [NEKO] - Unknown architecture: arm64
% uname -m
arm64
```
=> Fix build script for Apple Silicon MacOS.

client/src/components/video.vue
To determine if user has a touch device we used:
- check for `'ontouchstart' in window` or `navigator.maxTouchPoints > 0`
- check if pointer is not [fine](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer#fine).
- check if there is no hover.
There was however an issue with the last one. Some touch devices with Stylus do support hover and the keyboard icon was not shown. We would need to check if the user has no physical keyboard, rather that checking if they use touch device. But here is [no reliable way to do it](https://stackoverflow.com/questions/18880236/how-do-i-detect-hardware-keyboard-presence-with-javascript). So we removed the hover check and show the virtual keyboard button for all touch devices, even if would be touchscreens with mouse pointer and keyboard (as …
=> Fix mobile keyboard behavior

webpage/docs/quick-start.md
Fixed typo in doc for local - deocker-compose.yaml
=> Fix typo  in quick-start guide for local network setup

client/src/locale/id-id.ts, client/src/locale/index.ts
=> [id-id] Add Indonesian

server/internal/capture/manager.go, server/internal/config/capture.go, server/internal/config/capture_pipeline.go, webpage/docs/configuration/capture.md, webpage/docs/migration-from-v2/help.json, webpage/docs/migration-from-v2/help.txt
Allows us to have `{hostname}` in broadcast pipeline variables. In neko rooms, hostname contains the room name.
=> Add hostname to broadcast variables
