m1k1o/neko

.m1k1o/chromium/Dockerfile

See: https://github.com/macchrome/linchrome/releases/tag/v84.0.4147.89-r768962-portable-ungoogled-Lin64

Update Chromium to v84

---

server/cmd/serve.go
server/internal/broadcast/manager.go
server/internal/gst/gst.go
server/internal/types/config/broadcast.go
server/neko.go

This PR adds stereo support (only firefox as client supports this) and RTMP broadcast.
Also ability to add custom RTMP pipeline. With another codec etc..

Custom Broadcast Pipeline + stereo

---

client/src/components/avatar.vue
client/src/components/chat.vue
client/src/components/context.vue
client/src/components/members.vue

Custom avatars

---

client/src/neko/base.ts

Should fix https://github.com/m1k1o/neko/issues/29

should fix race condition

---

client/src/locale/fr-fr.ts
client/src/locale/index.ts

French i18n

---

README.md
client/src/components/video.vue

Mac os keyboard mapping

---

README.md
client/src/components/video.vue

Fast scroll speed on MacOS

---

.m1k1o/firefox/Dockerfile
.m1k1o/firefox/Dockerfile.arm
.m1k1o/firefox/profiles.ini
.m1k1o/firefox/supervisord.conf

Profile directory is chosen with random name everytime container is created, what makes it impossible for own customizations. This PR aims to set it to known value each time.
TODO:

Firefox profile directory

---

client/src/lib.ts

Lib build fix $te ref

---

server/internal/session/manager.go

Hi! I was trying out n.eko for the first time and noticed this typo.

Fix typo in log message

---

client/src/locale/de-de.ts
client/src/locale/index.ts

Hello everybody,
I've created the german language translation.
My college is nearly upset of your Project and wanted to use it as a daily driver.
I'm also really astonished, that it works so smoothly with Web-RTC.
Just let me know if you are need anykind of help with the Client/Server, I'm glad to help :)

Added german as language

---

client/src/components/resolution.vue
client/src/components/video.vue
client/src/neko/events.ts
client/src/neko/index.ts
client/src/neko/messages.ts
client/src/store/remote.ts
client/src/utils/index.ts
docs/changelog.md
server/internal/session/manager.go
server/internal/types/event/events.go
server/internal/types/message/messages.go
server/internal/types/session.go
server/internal/websocket/broadcast.go
server/internal/websocket/session.go

Clipboard is not syncing correctly.

Fix clipboard sync

---

client/src/components/context.vue
client/src/components/controls.vue
client/src/components/video.vue
client/src/locale/en-us.ts
client/src/locale/es-sp.ts
client/src/locale/fr-fr.ts
client/src/locale/nb-no.ts
client/src/locale/sk-sk.ts
client/src/locale/sv-se.ts
client/src/store/remote.ts
docs/changelog.md
server/internal/session/manager.go
server/internal/types/config/webrtc.go
server/internal/types/session.go
server/internal/types/webrtc.go
server/internal/webrtc/handle.go
server/internal/webrtc/webrtc.go
server/internal/websocket/admin.go
server/internal/websocket/control.go
server/internal/websocket/session.go
server/internal/websocket/websocket.go

User does not need to request control before moving/clicking on anything. He needs to do it as in his local browser. It might get a little chaotic with multiple people, since there can be only one cursor though.
Closes  #99.

Implicit control gain

---

client/src/locale/index.ts
client/src/locale/ru-ru.ts

add russian

---

docs/getting-started/README.md

docs fix spelling

---

.docker/firefox/policies.json

Just change default setting for firefox
https://github.com/m1k1o/neko/issues/160

FIX: Firefox context menu

---

README.md

(typo fix) Web RTC -> WebRTC

---

client/src/locale/index.ts
client/src/locale/zh-cn.ts

Hello everybody,
here my second contribution once again a language.
Many greetings
Phil

Added simplified chinese as language

---

docs/getting-started/configuration.md

this PR updates `Agruments` to `Arguments` in the docs

docs(configuration): fix typo

---

README.md

Please consider adding more info on the main page as the url arguments are pretty useful when looking to quickly share a room with friends, etc.

Updated Readme to include details about url args.

---

docs/changelog.md
docs/getting-started/configuration.md
server/internal/http/http.go
server/internal/types/config/server.go

https://github.com/m1k1o/neko/issues/196

Add path prefix

---

.docker/base/Dockerfile

Fixes emojis by adding Google's Noto Emoji.

Emoji support

---

docs/getting-started/README.md

perespective -> perspective
brwosing -> browsing

docs typo fixes

---

docs/README.md
docs/getting-started/README.md
docs/getting-started/configuration.md
docs/getting-started/reverse-proxy.md
docs/getting-started/troubleshooting.md

docs - fix typos

---

client/src/components/menu.vue
client/src/plugins/i18n.ts
docs/changelog.md
docs/getting-started/README.md

closes #295
Added lang parameter to the URL for default lang.
Should probably edit the README or the docs to reflect the change.

lang url parameter

---

.docker/base/Dockerfile
.docker/base/Dockerfile.arm
.docker/base/Dockerfile.intel
.docker/base/Dockerfile.nvidia
docs/changelog.md
server/build
server/neko.go

When docker images are built, they should contain curent git commit and git tag.

Add version to docker build

---

.docker/base/Dockerfile.arm
.github/workflows/ghcr-arm.yml

Building client on ARM pipelines fails 40% of the time, not sure why. And it takes very long (2 - 3hours). Therefore building it outside of docker.

Fix arm build

---

client/src/components/menu.vue
client/src/store/client.ts
docs/getting-started/README.md

added urlparameter for https://github.com/m1k1o/neko/issues/352

New urlparameter

---

docs/getting-started/reverse-proxy.md

Added the haproxy section in order to reverse proxy n.eko
Feel free to edit this section if you think it's needed ! 😀

chore(docs): Add haproxy in the reverse-proxy section

---

docs/getting-started/examples.md

Added example for persisting firefox settings.

Update examples.md with example for persisting firefox settings

---

client/src/locale/index.ts
client/src/locale/ja-jp.ts

I made Japanese localization.
Please merge it if you like.

Added Japanese localization

---

client/src/components/video.vue

Show keyboard icon on touch screen devices.
Fixes https://github.com/m1k1o/neko/issues/115
Related https://github.com/m1k1o/neko/issues/251

Show keyboard icon on touch screen devices

---

server/internal/http/manager.go

if we have legacy mode, we need to start local http server too. ref #504

Fix https legacy mode

---

client/src/components/video.vue
client/src/store/remote.ts

implicit hosting: request control prior interacting with the screen

---

README.md

update docker hub url
